# Generated by Django 5.2.8 on 2025-11-25 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoutineTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section", models.CharField(max_length=20)),
                ("emotional", models.BooleanField(default=False)),
                ("mental", models.BooleanField(default=False)),
                ("physical", models.BooleanField(default=False)),
                ("emotional_minutes", models.PositiveIntegerField(default=0)),
                ("mental_minutes", models.PositiveIntegerField(default=0)),
                ("physical_minutes", models.PositiveIntegerField(default=0)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
