# Generated by Django 5.2.8 on 2025-11-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_routinetracker"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="routinetracker",
            options={"ordering": ["-start_time"]},
        ),
        migrations.AddField(
            model_name="routinetracker",
            name="progress_percent",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
